"""empty message

Revision ID: 0792ef5a15dc
Revises: ffdc0a98111c
Create Date: 2021-07-28 16:26:37.000017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0792ef5a15dc'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('current_lat', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('current_long', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_long')
    op.drop_column('users', 'current_lat')
    op.drop_column('users', 'img_url')
    # ### end Alembic commands ###
