"""empty message

Revision ID: 6b1a1ee8618a
Revises: 482a09f14f01
Create Date: 2021-08-05 15:37:37.601783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1a1ee8618a'
down_revision = '482a09f14f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('card_image', sa.String(length=2000), nullable=True))
    op.add_column('businesses', sa.Column('banner_image', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'banner_image')
    op.drop_column('businesses', 'card_image')
    # ### end Alembic commands ###
